export const triviaQuestions = [
  "What is the capital of France?",
  "How many days are in a leap year?",
  "What color do you get mixing red and blue?",
  "What is 8 × 7?",
  "Name a planet with rings.",
  "What comes after Thursday?",
  "How many sides does a hexagon have?",
  "What is the largest ocean?",
  "Which animal is known as the King of the Jungle?",
  "What gas do humans breathe in to survive?",
  "Which country is famous for the Great Wall?",
  "Who wrote 'Romeo and Juliet'?",
  "What is the freezing point of water in Celsius?",
  "Which planet is closest to the sun?",
  "What is 25 + 37?",
  "Name the largest mammal on Earth.",
  "How many continents are there?",
  "Who painted the Mona Lisa?",
  "Which instrument has 88 keys?",
  "What is the chemical symbol for gold?",
  "Which language is primarily spoken in Brazil?",
  "Who discovered gravity?",
  "How many hours are in a day?",
  "What is the main ingredient in bread?",
  "What is 9 × 9?",
];

export const spellBackwardsQuestions = [
  "HELLO",
  "WORLD",
  "BRAIN",
  "FOCUS",
  "SWIFT",
  "DANCE",
  "MUSIC",
  "LIGHT",
  "POWER",
  "HAPPY",
  "QUICK",
  "SMART",
  "CHESS",
  "TRAIN",
  "PLANT",
  "GAMER",
  "NIGHT",
  "SOUND",
  "CLOUD",
  "PIXEL",
  "TABLE",
  "CHAIR",
  "RIVER",
  "OCEAN",
  "MOUNTAIN",
];
